name: peertuber
description: Opensource mobile app for PeerTube.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  internet_connection_checker_plus: ^2.0.0
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  flutter_hooks: ^0.20.1
  hooked_bloc: ^1.4.3
  miniplayer:
    git:
      url: https://github.com/PeerTuber/miniplayer
      ref: master
  timeago: ^3.5.0
  google_nav_bar: ^5.0.6
  media_kit: ^1.1.8+2 # Primary media package.
  media_kit_video: ^1.2.1 # For video rendering.
  media_kit_libs_video: ^1.0.3 # Native video dependencies.
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^2.3.0
  get_it: ^7.6.4
  json_annotation: ^4.8.0
  go_router: ^11.0.0
  easy_localization: ^3.0.3
  formz: ^0.6.1
  hive: ^2.2.3
  sliding_up_panel2: ^3.3.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
